// <auto-generated />
using BSU_BackpackToGithub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BSU_BackpackToGithub.Migrations
{
    [DbContext(typeof(BSUStudentContext))]
    [Migration("20191108181143_StudentRegex")]
    partial class StudentRegex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("BSU_BackPackToGithub.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Number");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("BSU_BackPackToGithub.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BSU_Username")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<int>("ClassFK");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("GitHub_Username")
                        .IsRequired()
                        .HasMaxLength(39);

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(78);

                    b.HasKey("Id");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
