// <auto-generated />
using BSU_BackpackToGithub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BSU_BackpackToGithub.Migrations
{
    [DbContext(typeof(BSUStudentContext))]
    partial class BSUStudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BSU_BackPackToGithub.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Number");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("BSU_BackPackToGithub.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BSU_Username")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<int>("ClassFK");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("GitHub_Username")
                        .IsRequired()
                        .HasMaxLength(39);

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(78);

                    b.HasKey("Id");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
